# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ee1cb45ba245e641994998ed47e3b47aa96f95239bed5b226d8d7b3ec61103b846cf86b888a046e90d52803eea6da48af6de037d4c253d5e497b008e70cca1

test:
  secret_key_base: 83a26a7b93db5aae3e8f96c13edb46ac0bd0612630bb67b1b94929f79127c1ea1f41cfb561c3869c94e5f578f14b674806e5f5b4b0285f81e610bba616ee10a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
